# Generated by Django 2.1.3 on 2018-11-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='down_votes',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='up_votes',
            field=models.IntegerField(default=1),
        ),
    ]
