# Generated by Django 2.1.3 on 2018-11-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_auto_20181130_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='down_votes',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='answer',
            name='up_votes',
            field=models.IntegerField(default=1),
        ),
    ]
